# Project information
site_name: Aiogram 3 FAQ
site_url: https://akchonya.github.io/aiogram-3-faq

# Repository
repo_name: akchonya/aiogram-3-faq
repo_url: https://github.com/akchonya/aiogram-3-faq


theme:
  favicon: images/favicon.ico
  name: material
  
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: blue grey

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: blue grey

  icon:
    logo: material/book-cog
    

# Navigation
nav:
  - 'Introduction': index.md
  - 'Prior Knowlegde': prior_knowledge.md
  - 'Deeper Knowledge': deeper_knowledge.md
  - 'Common Questions': common_questions.md
  - 'Common Errors': common_errors.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true

# Extras
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/aiofaqbot
      name: Telegram Bot
    - icon: fontawesome/brands/github
      link: https://github.com/akchonya
      name: GitHub
  meta:
    - name: "google-site-verification"
      content: "l8Y9vTG_P-ElVlvKL9qb7uGf_jh3aQMC5iBrGT7iuX4"
